application: provasketch
version: 3
runtime: python
api_version: 1
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 )$


handlers:

- url: /sketchNotMadePublicNotice.html
  static_files: sketchNotMadePublicNotice.html
  upload: sketchNotMadePublicNotice.html

- url: /gallery.html
  static_files: galleryPage/gallery.html
  upload: galleryPage/gallery.html

- url: /galleryPage/
  static_dir: galleryPage/

- url: /galleryview_files/
  static_dir: galleryPage/galleryview_files/

- url: /tutorial/
  static_dir: tutorial/

- url: /groupLoginNotOK.html
  static_files: groupLoginNotOK.html
  upload: groupLoginNotOK.html

- url: /frontPageFiles/images
  static_dir: frontPageFiles/images
  expiration: "1h"

- url: /P5Lint/tests
  static_dir: P5Lint/tests
  mime_type: text.plain

- url: /P5Lint
  static_dir: P5Lint

- url: /sandbox.html
  static_dir: sandbox_files

- url: /sketchPlayer
  static_dir: sketchPlayer

- url: /img
  static_dir: img

- url: /wallpapers
  static_dir: wallpapers

- url: /jscripts
  static_dir: jscripts

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /about.html
  static_files: about.html
  upload: about.html

- url: /labs.html
  static_files: labs.html
  upload: labs.html

- url: /extras.html
  static_files: extras.html
  upload: extras.html

- url: /500th.html
  static_files: 500th.html
  upload: 500th.html

- url: /Featured_artist.html
  static_files: Featured_artist.html
  upload: Featured_artist.html

- url: /featuredSketches
  static_dir: featuredSketches

- url: /labs
  static_dir: labs

- url: /livecodelab
  static_dir: livecodelab

- url: /Featured_Sketches.html
  static_files: Featured_Sketches.html
  upload: Featured_Sketches.html

- url: /comments.html
  static_files: comments.html
  upload: comments.html
  
- url: /footer.html
  static_files: footer.html
  upload: footer.html
  
- url: /referenceGalleryDesign.html
  static_files: referenceGalleryDesign.html
  upload: referenceGalleryDesign.html
  
- url: /links.html
  static_files: links.html
  upload: links.html
  
- url: /newSketch.html
  static_files: newSketch.html
  upload: newSketch.html
  
- url: /Tutorial.html
  static_files: Tutorial.html
  upload: Tutorial.html

- url: /style.css
  static_files: style.css
  upload: style.css
    
- url: /jquery.boxy.js
  static_files: jquery.boxy.js
  upload: jquery.boxy.js
  
- url: /static
  static_dir: static

- url: /imgs
  static_dir: imgs

- url: /jquery-tooltip
  static_dir: jquery-tooltip
  
- url: /cornerTest.html
  static_files: cornerTest.html
  upload: cornerTest.html
  
- url: /corner
  static_dir: corner
  
- url: /boxy
  static_dir: boxy
# ------------- BLOG -------------

- url: /tinymce/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

#- url: /tinymce
#  static_dir: BLOG/tinymce  
  
- url: /blog/static
  static_dir: BLOG/static

- url: /BLOG/rpc|/BLOG/xmlrpc\.php|/BLOG/rpc/.*
  script: BLOG/api_rpc.py

- url: /blog/themes/default/style.css
  static_files: BLOG/themes/default/style.css
  upload: BLOG/themes/default/style.css

- url: /blog/themes/.*
  script: BLOG/theme_files.py

- url: /blog/myadmin/.*|/blog/myadmin
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /blog/admin/post|/blog/admin/entries/(post|page)|/blog/admin/links|/blog/admin/categories|/blog/admin/comments
  script: BLOG/admin.py
  login: required

- url: /blog/admin/{0,1}
  script: BLOG/admin.py
  login: required

- url: /blog/admin/link|/blog/admin/category|/blog/admin/(post|page)|/blog/admin/lang|/blog/admin/filemanager|/blog/admin/upload|/blog/admin/uploadex
  script: BLOG/admin.py
  login: required

- url: /blog/admin/.*
  script: BLOG/admin.py
  login: admin
  
- url: /blog/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /blog/.*
  script: BLOG/blog.py

### FORUM ###

- url: /forum/static
  static_dir: FORUM/static

- url: /forum/img
  static_dir: FORUM/img

- url: /forum/.*
  script: FORUM/main.py

- url: /forumList/.*
  script: FORUM/main.py

# these two should be the last ones

  
- url: /.*
  script: main.py

